<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrxodgT\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrxodgT/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXrxodgT.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXrxodgT\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXrxodgT\App_KernelProdContainer([
    'container.build_hash' => 'XrxodgT',
    'container.build_id' => 'dd23e7af',
    'container.build_time' => 1597952548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrxodgT');
