<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVeR3U7g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVeR3U7g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVeR3U7g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVeR3U7g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVeR3U7g\App_KernelDevDebugContainer([
    'container.build_hash' => 'VeR3U7g',
    'container.build_id' => '9c0eed4e',
    'container.build_time' => 1597949655,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVeR3U7g');
